@startuml
skinparam dpi 100
hide footbox

box "Platform" #LightBlue
  participant "CPO1" as CPO1
end box

participant "HUB" as HUB

box "Platform" #LightBlue
  participant "eMSP1" as MSP1
end box
box "Platform" #LightBlue
  participant "eMSP2" as MSP2
end box
box "Platform" #LightBlue
  participant "eMSP3" as MSP3
end box

CPO1 -> HUB: HTTP: GET\nFROM: CPO1
activate CPO1
activate HUB
HUB --> HUB: Determine\nrouting
HUB -> MSP2: HTTP: GET\nTO: MSP2\nFROM: CPO1
activate MSP2
MSP2 -> HUB: HTTP: RESPONSE 200\nTO: CPO1\nFROM: MSP2
deactivate MSP2
HUB -> CPO1: HTTP: RESPONSE 200\nTO: CPO1\nFROM: MSP2
deactivate CPO1

deactivate HUB
@enduml