:numbered:
[[credentials_credentials_endpoint]]
== _Credentials_ module

*Module Identifier: `credentials`*

The credentials module is used the exchange the credentials token that has to be used by parties for authorization.

Every OCPI request is required to contain a credentials token in a <<transport_and_format.asciidoc#transport_and_format_authorization_header,HTTP Authorization header>>.


[[credentials_use_cases]]
=== Use cases

[[credentials_registration]]
==== Registration

To register a CPO in an eMSP platform (or vice versa), the CPO must create a unique credentials token that can be used for authenticating the eMSP.
This credentials token along with the versions endpoint should be sent to the eMSP in a secure way that is outside the scope of this protocol.

`CREDENTIALS_TOKEN_A` is given offline, after registration store the `CREDENTIALS_TOKEN_C` which will be used in future exchanges.
The `CREDENTIALS_TOKEN_A` can then be thrown away.

The eMSP starts the registration process, retrieves the version information and details (using `CREDENTIALS_TOKEN_A` in the HTTP Authorization header).
The eMSP generates `CREDENTIALS_TOKEN_B`, send it to the CPO in a POST request to the `credentials` module of the CPO.
The CPO stores `CREDENTIALS_TOKEN_B` and uses it for any requests to the eMSP, including the version information and details.

(In the sequence diagrams below we use relative paths as short resource identifiers to illustrate a point;
please note that they should really be absolute URLs in any working implementation of OCPI)

.The OCPI registration process
image::images/registration-sequence.svg[The OCPI registration process]

Due to its symmetric nature, the CPO and eMSP can be swapped in the registration sequence.


[[credentials_updating_to_a_newer_version]]
==== Updating to a newer version

At some point both parties will have implemented a newer OCPI version. To start using the newer version, one party has to send a PUT request to the credentials endpoint of the other party.

.The OCPI update process
image::images/update-sequence.svg[The OCPI update process]

[[credentials_changing_endpoints_for_the_current_version]]
==== Changing endpoints for the current version

This can be done by following the update procedure for the same version. By sending a PUT request to the credentials endpoint of this version, the other party will fetch and store the corresponding set of endpoints.

[[credentials_updating_the_credentials_and_resetting_the_token]]
==== Updating the credentials and resetting the credentials token

The credentials (or parts thereof, such as the credentials token) can be updated by sending the new credentials via
a PUT request to the credentials endpoint of the current version, similar to the update procedure described above.

[[credentials_errors_during_registration]]
==== Errors during registration

When the Server connects back to the client during the credentials registration, it might encounter problems.
When this happens, the Server should add the status code: <<status_codes.asciidoc#status_codes_3xxx_server_errors,3001>>
in the response to the POST from the client.

[[credentials_required_endpoints_not_available]]
==== Required endpoints not available

When two parties connect, it might happen that one of the parties expects a certain endpoint to be available at the other party.

For example: a CPO could only want to connect when the CDRs endpoint is available in an eMSP system.

In case the client is starting the credentials exchange process and cannot find the endpoints it expects,
it is expected NOT to send the POST request with credentials to the server.
Log a message/notify the administrator to contact the administrator of the server system.

In case the server, receiving the request from a client, cannot find the endpoints it expects,
then it is expected to respond to the request with a status code: <<status_codes.asciidoc#status_codes_3xxx_server_errors,3003>>.


[[credentials_interfaces_and_endpoints]]
=== Interfaces and endpoints

Example: `/ocpi/cpo/2.2/credentials` and `/ocpi/emsp/2.2/credentials`

[cols="2,12",options="header"]
|===
|Method |Description 

|<<credentials_get_method,GET>> |Retrieves the credentials object to access the server's platform. 
|<<credentials_post_method,POST>> |Provides the server with a credentials object to access the client's system (i.e. register). 
|<<credentials_put_method,PUT>> |Provides the server with an updated credentials object to access the client's system. 
|PATCH |n/a 
|<<credentials_delete_method,DELETE>> |Informs the server that its credentials to the client's system are now invalid (i.e. unregister). 
|===

[[credentials_get_method]]
==== *GET* Method

Retrieves the credentials object to access the server's platform. The request body is empty, the response contains the credentials object to access the server's platform. This credentials object also contains extra information about the server such as its business details.

[[credentials_post_method]]
==== *POST* Method

Provides the server with credentials to access the client's system. This credentials object also contains extra information about the client such as its business details.

A `POST` initiates the registration process for this endpoint's version. The server must also fetch the client's endpoints for this version.

If successful, the server must generate a new credentials token and respond with the client's new credentials to access the server's system. The credentials object in the response also contains extra information about the server such as its business details.

This must return a `HTTP status code 405: method not allowed` if the client was already registered.

[[credentials_put_method]]
==== *PUT* Method

Provides the server with updated credentials to access the client's system. This credentials object also contains extra information about the client such as its business details.

A `PUT` will switch to the version that contains this credentials endpoint if it's different from the current version. The server must fetch the client's endpoints again, even if the version has not changed.

If successful, the server must generate a new credentials token for the client and respond with the client's updated credentials to access the server's system. The credentials object in the response also contains extra information about the server such as its business details.

This must return a `HTTP status code 405: method not allowed` if the client was not registered yet.

[[credentials_delete_method]]
==== *DELETE* Method

Informs the server that its credentials to access the client's system are now invalid and can no longer be used. Both parties must end any automated communication. This is the unregistration process.

This must return a `HTTP status code 405: method not allowed` if the client was not registered.


[[credentials_object_description]]
=== Object description

[[credentials_credentials_object]]
==== Credentials object

[cols="3,3,1,9",options="header"]
|===
|Property |Type |Card. |Description 

|token |<<types.asciidoc#types_string_type,string>>(64) |1 |The credentials token for the other party to authenticate in your system.
|url |<<types.asciidoc#types_url_type,URL>> |1 |The URL to your API versions endpoint. 
|roles |<<credentials_credentials_role_class,CredentialsRole>> |+ |List of the roles this party provides.
|===

Every role needs a unique combination of: role, party_id and country_code.

A party can have the some role more then once, for example when a CPO provides 'white label' services for virtual CPOs.

One or more roles and thus `party_id` and `country_code` sets are provided here to inform a server about the `party_id` and `country_code`
sets a client will use when pushing <<transport_and_format.asciidoc#transport_and_format_client_owned_object_push,client owned objects>>.
This helps a server determine the URLs a client will use when pushing
a <<transport_and_format.asciidoc#transport_and_format_client_owned_object_push,client owned object>>.
The `country_code` is added the make certain the URL used when pushing
a <<transport_and_format.asciidoc#transport_and_format_client_owned_object_push,client owned object>> is unique,
there might be multiple parties in the world with the same `party_id`, but the combination should always be unique.
A party operating in multiple countries can always use the home country of the company for all connections.

For example: an OCPI implementation might push EVSE IDs from a company for different countries,
preventing an OCPI connection per country a company is operating in.

The `party_id` and `country_code` give here, have no direct link with the eMI3 EVSE IDs and Contract IDs that might be used in the different OCPI modules.

For example: an party implementing OCPI might push EVSE IDs with an eMI3 `spot operator` different from the OCPI `party_id` and/or the `country_code`.

[[credentials_example]]
==== Example

[source,json]
----
include::examples/credentials_example.json[]
----


=== Data types

[[credentials_credentials_role_class]]
==== CredentialsRole _class_

[cols="3,3,1,9",options="header"]
|===
|Property |Type |Card. |Description

|role |<<credentials_credentials_role_enum,Role>> |1 |Type of Role.
|business_details |<<mod_locations.asciidoc#mod_locations_businessdetails_class,BusinessDetails>> |1 |Details of this party.
|party_id |<<types.asciidoc#types_cistring_type,CiString>>(3) |1 |CPO, eMSP (or other role) ID of this party. (following the 15118 ISO standard).
|country_code |<<types.asciidoc#types_cistring_type,CiString>>(2) |1 |Country code of the country this party is operating in.
|===

[[credentials_credentials_role_enum]]
==== Role _enum_

|===
|Value |Description

|CPO |Charge Point Operator Role
|MSP |eMobility Service Provider Role
|HUB |Hub role
|NSP |Navigation Service Provider Role
|OTHER |Other role
|SCSP|Smart Charging Service Provider Role
|===


