:numbered:
== _Tokens_ module

*Module Identifier: `tokens`*

The tokens module gives CPOs knowledge of the token information of an eMSP.
eMSPs can push Token information to CPOs, CPOs can build a cache of known Tokens.
When a request to authorize comes from a Charge Point, the CPO can check against this cache.
With this cached information they know to which eMSP they can later send a CDR. 

=== Flow and Lifecycle

==== Push model

When the MSP creates a new Token object they push it to the CPO by calling link:#212-put-method[PUT] on the CPO's Tokens endpoint with the newly created Token object.

Any changes to Token in the eMSP system are sent to the CPO system by calling either the link:#212-put-method[PUT] or the link:#213-patch-method[PATCH] on the CPO's Tokens endpoint with the updated Token(s).

When the eMSP invalidates a Token (deleting is not possible), the eMSP will send the updated Token (with the field: valid set to `false`, by calling, either the link:#212-put-method[PUT] or the link:#213-patch-method[PATCH] on the CPO's Tokens endpoint with the updated Token. 

When the eMSP is not sure about the state or existence of a Token object in the CPO system, the
eMSP can call the link:#221-get-method[GET] to validate the Token object in the CPO system. 

==== Pull model

When a CPO is not sure about the state of the list of known Tokens, or wants to request the full
list as a start-up of their system, the CPO can call the link:#221-get-method[GET] on the eMSP's Token endpoint to receive
all Tokens, updating already known Tokens and adding new received Tokens to it own list of Tokens.
This is not intended for real-time operation, requesting the full list of tokens for every authorization will put to much strain on systems.
It is intended for getting in-sync with the server, or to get a list of all tokens (from a server without push) every X hours.

==== Real-time authorization

An eMSP might want their Tokens to be authorizated 'real-time', not white-listed. For this the eMSP has to implement the link:#222-post-method[POST Authorize request] and set the Token.whitelist field to `NEVER` for Tokens they want to have authorized 'real-time'.

If an eMSP doesn't want real-time authorization, the link:#222-post-method[POST Authorize request] doesn't have to be implemented as long as all their Tokens have Token.whitelist set to `ALWAYS`. 

=== Interfaces and endpoints

There is both a CPO and an eMSP interface for Tokens. It is advised to use the push direction from eMSP to CPO during normal operation.
The eMSP interface is meant to be used when the CPO is not 100% sure the Token cache is still correct.

==== CPO Interface

With this interface the eMSP can push the Token information to the CPO.
Tokens is a link:transport_and_format.md#client-owned-object-push[client owned object], so the end-points need to contain the required extra fields: {link:credentials.md#credentials-object[party_id]} and {link:credentials.md#credentials-object[country_code]}.
Example endpoint structure:
`/ocpi/cpo/2.0/tokens/{country_code}/{party_id}/{token_uid}` 

|===
|Method |Description 

|link:#211-post-method[GET] |Retrieve a Token as it is stored in the CPO system. 
|POST |n/a 
|link:#212-put-method[PUT] |Push new/updated Token object to the CPO. 
|link:#213-put-method[PATCH] |Notify the CPO of partial updates to a Token. 
|DELETE |n/a, (Use link:#212-put-method[PUT], Tokens cannot be removed). 
|===

===== *GET* Method

If the eMSP wants to check the status of a Token in the CPO system it might GET the object from the CPO system for validation purposes. The eMSP is the owner of the objects, so it would be illogical if the CPO system had a different status or was missing an object.

====== Request Parameters

The following parameters can be provided as URL segments.

|===
|Parameter |Datatype |Required |Description 

|country_code |link:types.md#15-string-type[string](2) |yes |Country code of the eMSP requesting this GET from the CPO system. 
|party_id |link:types.md#15-string-type[string](3) |yes |Party ID (Provider ID) of the eMSP requesting this GET from the CPO system. 
|token_uid |link:types.md#15-string-type[string](36) |yes |Token.uid of the Token object to retrieve. 
|===

====== Response Data

The response contains the requested object. 

|===
|Type |Card. |Description 

|link:#32-token-object[Token] |1 |The requested Token object. 
|===

===== *PUT* Method

New or updated Token objects are pushed from the eMSP to the CPO. 

====== Request Body

In the put request a new or updated Token object is sent.

|===
|Type |Card. |Description 

|link:#32-token-object[Token] |1 |New or updated Token object. 
|===

====== Request Parameters

The following parameters can be provided as URL segments.

|===
|Parameter |Datatype |Required |Description 

|country_code |link:types.md#15-string-type[string](2) |yes |Country code of the eMSP sending this PUT request to the CPO system. 
|party_id |link:types.md#15-string-type[string](3) |yes |Party ID (Provider ID) of the eMSP sending this PUT request to the CPO system. 
|token_uid |link:types.md#15-string-type[string](36) |yes |Token.uid of the (new) Token object (to replace). 
|===

====== Example: put a new Token

[source,json]
----
PUT To URL: https://www.server.com/ocpi/cpo/2.0/tokens/NL/TNM/012345678

{
  "uid": "012345678",
  "type": "RFID",
  "auth_id": "DE8ACC12E46L89",
  "visual_number": "DF000-2001-8999",
  "issuer": "TheNewMotion",
  "valid": true,
  "whitelist": "ALWAYS",
  "last_updated": "2015-06-29T22:39:09Z"
}
----


===== *PATCH* Method

Same as the link:#212-put-method[PUT] method, but only the fields/objects that have to be updated have to be present, other fields/objects that are not specified are considered unchanged.

====== Example: invalidate a Token

[source,json]
----
PATCH To URL: https://www.server.com/ocpi/cpo/2.0/tokens/NL/TNM/012345678

{
  "valid": false
}
----

==== eMSP Interface

This interface enables the CPO to request the current list of Tokens, when needed.
Via the POST method it is possible to authorize a single token.

Example endpoint structure: `/ocpi/emsp/2.0/tokens/?date_from=xxx&amp;date_to=yyy`

|===
|Method |Description 

|link:#221-get-method[GET] |Get the list of known Tokens, last updated between the {date_from} and {date_to} (link:transport_and_format.md#get[paginated]) 
|link:#222-post-method[POST] |Real-time authorization request 
|PUT |n/a 
|PATCH |n/a 
|DELETE |n/a 
|===

===== *GET* Method

Fetch information about Tokens known in the eMSP systems.

====== Request Parameters

If additional parameters: {date_from} and/or {date_to} are provided, only Tokens with (`last_updated`) between the given date_from and date_to will be returned.

This request is link:transport_and_format.md#get[paginated], it supports the link:transport_and_format.md#paginated-request[pagination] related URL parameters.

|===
|Parameter |Datatype |Required |Description 

|date_from |link:types.md#12-datetime-type[DateTime] |no |Only return Tokens that have `last_updated` after this Date/Time. 
|date_to |link:types.md#12-datetime-type[DateTime] |no |Only return Tokens that have `last_updated` before this Date/Time. 
|offset |int |no |The offset of the first object returned. Default is 0. 
|limit |int |no |Maximum number of objects to GET. 
|===

====== Response Data

The endpoint response with list of valid Token objects, the header will contain the link:transport_and_format.md#paginated-response[pagination] related headers. 

Any older information that is not specified in the response is considered as no longer valid.
Each object must contain all required fields. Fields that are not specified may be considered as null values.

|===
|Type |Card. |Description 

|link:#32-token-object[Token] |* |List of all tokens. 
|===

===== *POST* Method

Do a 'real-time' authorization request to the eMSP system, validating if a Token might be used (at the optionally given Location). 

Example endpoint structure:
`/ocpi/emsp/2.0/tokens/{token_uid}/authorize?{type=token_type}`
The `/authorize` is required for the real-time authorize request.

When the eMSP receives a 'real-time' authorization request from a CPO that contains too little information (no LocationReferences provided) to determine if the Token might be used, the eMSP SHOULD respond with the OCPI status: link:status_codes.md#2xxx-client-errors[2002] 

====== Request Parameters

The following parameter has to be provided as URL segments.

|===
|Parameter |Datatype |Required |Description 

|token_uid |link:types.md#15-string-type[string](36) |yes |Token.uid of the Token for which this authorization is. 
|token_type |link:#43-tokentype-enum[TokenType] |no |Token.type of the Token for which this authorization is. Default if omitted: link:#43-tokentype-enum[RFID] 
|===

====== Request Body

In the body an optional link:#42-locationreferences-class[LocationReferences] object can be given. The eMSP SHALL then validate if the Token is allowed to be used at this Location, and if applicable: which of the Locations EVSEs/Connectors.
The object with valid Location and EVSEs/Connectors will be returned in the response.

|===
|Type |Card. |Description 

|link:#42-locationreferences-class[LocationReferences] |? |Location and EVSEs/Connectos for which the Token is requested to be authorized. 
|===

====== Response Data

The endpoint response contains a link:#31-authorizationinfo-object[AuthorizationInfo] object.

|===
|Type |Card. |Description 

|link:#31-authorizationinfo-object[AuthorizationInfo] |1 |Contains information about the authorization, if the Token is allowed to charge and optionally which EVSEs/Connectors are allowed to be used. 
|===

=== Object description

==== _AuthorizationInfo_ Object

|===
|Property |Type |Card. |Description 

|allowed |link:#41-allowed-enum[Allowed] |1 |Status of the Token, and whether charging is allowed at the optionally given location. 
|location |link:#42-locationreferences-class[LocationReferences] |? |Optional reference to the location if it was included in the request, and if the EV driver is allowed to charge at that location. Only the EVSEs/Connectors the EV driver is allowed to charge at are returned. 
|info |link:types.md#13-displaytext-class[DisplayText] |? |Optional display text, additional information to the EV driver. 
|===


==== _Token_ Object

|===
|Property |Type |Card. |Description 

|uid |link:types.md#15-string-type[string](36) |1 |Identification used by CPO system to identify this token. Currently, in most cases, this is the RFID hidden ID as read by the RFID reader. 
|type |link:#43-tokentype-enum[TokenType] |1 |Type of the token 
|auth_id |link:types.md#15-string-type[string](36) |1 |Uniquely identifies the EV Driver contract token within the eMSP's platform (and suboperator platforms). Recommended to follow the specification for eMA ID from "eMI3 standard version V1.0" (http://emi3group.com/documents-links/[http://emi3group.com/documents-links/]) "Part 2: business objects." 
|visual_number |link:types.md#15-string-type[string](64) |? |Visual readable number/identification as printed on the Token (RFID card), might be equal to the auth_id. 
|issuer |link:types.md#15-string-type[string](64) |1 |Issuing company, most of the times the name of the company printed on the token (RFID card), not necessarily the eMSP. 
|valid |boolean |1 |Is this Token valid 
|whitelist |link:#44-whitelisttype-enum[WhitelistType] |1 |Indicates what type of white-listing is allowed. 
|language |link:types.md#15-string-type[string](2) |? |Language Code ISO 639-1. This optional field indicates the Token owner's preferred interface language. If the language is not provided or not supported then the CPO is free to choose its own language. 
|last_updated |link:types.md#12-datetime-type[DateTime] |1 |Timestamp when this Token was last updated (or created). 
|===

The combination of _uid_ and _type_ should be unique for every token within the eMSP's system.

===== Example

[source,json]
----
{
  "uid": "012345678",
  "type": "RFID",
  "auth_id": "DE8ACC12E46L89",
  "visual_number": "DF000-2001-8999",
  "issuer": "TheNewMotion",
  "valid": true,
  "whitelist": "ALLOWED",
  "last_updated": "2015-06-29T22:39:09Z"
}
----

=== Data types

==== Allowed _enum_

|===
|Value |Description 

|ALLOWED |This Token is allowed to charge at this location. 
|BLOCKED |This Token is blocked. 
|EXPIRED |This Token has expired. 
|NO_CREDIT |This Token belongs to an account that has not enough credits to charge at the given location. 
|NOT_ALLOWED |Token is valid, but is not allowed to charge at the given location. 
|===

==== LocationReferences _class_

References to location details.

|===
|Field Name |Field Type |Card. |Description 

|location_id |link:types.md#15-string-type[string](39) |1 |Unique identifier for the location. 
|evse_uids |link:types.md#15-string-type[string](39) |* |Unique identifier for EVSEs within the CPO's platform for the EVSE within the the given location. 
|connector_ids |link:types.md#15-string-type[string](36) |* |Identifies the connectors within the given EVSEs. | 
|===

==== TokenType _enum_

|===
|Value |Description 

|OTHER |Other type of token 
|RFID |RFID Token 
|===

==== WhitelistType _enum_

Defines when authorization of a Token by the CPO is allowed. 

|===
|Value |Description 

|ALWAYS |Token always has to be whitelisted, link:mod_tokens.md#13-real-time-authorization[realtime authorization] is not possible/allowed. 
|ALLOWED |It is allowed to whitelist the token, link:mod_tokens.md#13-real-time-authorization[realtime authorization] is also allowed. 
|ALLOWED_OFFLINE |Whitelisting is only allowed when CPO cannot reach the eMSP (communication between CPO and eMSP is offline) 
|NEVER |Whitelisting is forbidden, only link:mod_tokens.md#13-real-time-authorization[realtime authorization] is allowed. Token should always be authorized by the eMSP. 
|===