[[terminology_terminology_and_definitions]]
== Terminology and Definitions

[[terminology_abbreviations]]
=== Abbreviations

* *OCPI* Open Charge Point Interface
* *OCPP* Open Charge Point Protocol
* *CDR* Charge Detail Record
* *CPO* Charging Point Operator
* *eMSP* e-Mobility Service Provider

[[terminology_provider_and_operator_abbreviation]]
=== Provider and Operator abbreviation

In OCPI it is advised to use eMI3 compliant names for Contract IDs and EVSE IDs. The provider and the operator name is important here, in order to target the right provider or operator, they need to be known up front, at least between the cooperating parties. 

In several standards, an issuing authority is mentioned that will keep a central registry of known Providers and Operators.
At this moment, the following countries have an authority that keeps track of the known providers and operators:

[[terminology_the_netherlands]]
==== The Netherlands

The Dutch foundation, named http://www.eviolin.nl[eViolin] keeps the registry for The Netherlands. 

* The list of operator IDs and provider IDs can be viewed on their website http://www.eviolin.nl/index.php/leden/[eViolin/Leden].

[[terminology_germany]]
==== Germany

The BDEW organisation keeps the registry for Germany in their general code number service https://bdew-codes.de/[bdew-codes.de].

* https://bdew-codes.de/Codenumbers/EMobilityId/ProviderIdList[Provider ID List] See https://bdew-codes.de/Codenumbers/EMobilityId/ProviderIdList[https://bdew-codes.de/Codenumbers/EMobilityId/ProviderIdList]
* https://bdew-codes.de/Codenumbers/EMobilityId/OperatorIdList[EVSE Operator ID List] See https://bdew-codes.de/Codenumbers/EMobilityId/OperatorIdList[https://bdew-codes.de/Codenumbers/EMobilityId/OperatorIdList]

[[terminology_austria]]
==== Austria

Austrian Mobile Power GmbH maintains a registry for Austria. This list is not publicly available.
For more information visit http://austrian-mobile-power.at/tools/id-vergabe/information/[austrian-mobile-power.at]

[[terminology_france]]
==== France

The AFIREV* organisation will keep/keeps the registry for France. It provides operation Id for CPO and eMSP in compliance with eMI3 id structure. The prefix of these Ids is the “fr” country code. AFIREV will also be in charge of the definition of EVSE-Id structure, Charging-Pool-Id structure (location), and Contract-Id structure for France. AFIREV bases its requirements and recommendations on eMI3 definitions.

AFIREV stands for: Association Française pour l’Itinérance de la Recharge Électrique des Véhicules

[[terminology_charging_topology]]
=== Charging topology

The charging topology, as relevant to the eMSP, consists of three entities:

* _Connector_ is a specific socket or cable available for the EV to make use of.
* _EVSE_ is the part that controls the power supply to a single EV in a single session. An EVSE may provide multiple connectors but only one of these can be active at the same time.
* _Location_ is a group of one or more EVSEs that belong together geographically or spatially.

.Topology
image::images/topology.svg[Topology]

A Location is typically the exact location of one or more EVSEs, but it can also be the entrance of a parking garage or a gated community. It is up to the CPO to use whatever makes the most sense in a specific situation. Once arrived at the location, any further instructions to reach the EVSE from the Location are stored in the EVSE object itself (such as the floor number, visual identification or manual instructions).

[[terminology_variable_names]]
=== Variable names

In order to prevent issues with Capitals in variable names, the naming in JSON is not CamelCase but snake_case. All variables are lowercase and include an underscore for a space.

[[terminology_cardinality]]
=== Cardinality

When defining the cardinality of a field, the following symbols are used throughout this document:

|===
|Symbol |Description |Type 

|? |An optional object. If not set, it might be `null`, or the field might be omitted. When the field is omitted and it has a default value, the value is the default value. |Object 
|1 |Required object. |Object 
|* |A list of zero or more objects. If empty, it might be `null`, `[]` or the field might be omitted. |[Object] 
|+ |A list of at least one object. |[Object] 
|===