[[terminology_terminology_and_definitions]]
== Terminology and Definitions

[[terminology_abbreviations]]
=== Abbreviations

[cols="2s,10",options="header"]
|===
|Abbr. |Description
|CDR   |Charge Detail Record
|CPO   |Charging Point Operator
|eMSP  |e-Mobility Service Provider
|NSP   |Navigation Service Provider
|OCPP  |Open Charge Point Protocol
|===


[[terminology_roles]]
=== EV Charging Market Roles

In the EV Charging landscape, different market roles can be identified.

[cols="3s,9",options="header"]
|===
|Role  |Description
|CPO   |Charging Point Operator
|eMSP  |e-Mobility Service Provider
|Hub   |Can connector one or more CPOs to one or more eMSPs.
|NSP   |Provides EV drivers with location information of Charge Points.
|Roaming Hub |See: Hub
|===

Some of these roles can be combined in one company. A Platform can provides service for multiple CPOs or eMSP,
but also for both eMSPs and CPOs.

OCPI 2.0/2.1.1 had a very strict definition or roles: only CPO and eMSP. But this is rare in the real world,
there are almost no parties that are strict CPO or eMSP and have there own platform. In the real-world, lots of
parties provide service to CPOs that are not running their own platform.
A lot of CPOs are also eMSP. With OCPI 2.1.1 and earlier that mend having to setup a OCPI connection per role.

OCPI 2.2 introduces more roles and abstracts the role from the OCPI connection.
OCPI 2.2 talks about Platforms connection to Platforms, or Platforms connecting via Hubs to other Platforms.
The Platform itself is not a role. The Platform provides services for 1 or more roles.

Examples of platforms:

* A pure CPO, not providing services to other CPOs, not being an eMSP, running its own software that connects via OCPI.
  Is defined in OCPI as a Platform has 1 CPO role, the CPO role of that company.
* A Company that has a cloud based eMSP software solution,
  it offers to companies that want to be eMSP, but don't want to host/run their own software,
  is a Platform that has a number of eMSP roles, one for each eMSP the company is providing services for.
  But not for the company itself because the company itself is not an eMSP.
* A Company that operates public Charge Points, also provides eMSP service to EV drivers, running their own software platform,
  is seen in OCPI as a Platform that has 2 roles: CPO and eMSP for this company.
* If the company above starts to offer their service to other CPOs and eMSP, it is still seen as 1 platform,
  but then with multiple CPO and eMSP roles.


[[terminology_terms]]
=== Terminology

[cols="3s,9",options="header"]
|===
|Term  |Description
|Platform | Software that provides services via OCPI.
            A platform can provide service for a single eMSP or CPO, or for multiple CPOs or eMSPs.
            It can even provide services for both eMSPs and CPOs at the same time.
|===


[[terminology_provider_and_operator_abbreviation]]
=== Provider and Operator abbreviation

In OCPI it is advised to use eMI3 compliant names for Contract IDs and EVSE IDs. The provider and the operator name is important here,
in order to target the right provider or operator, they need to be known up front, at least between the cooperating parties.

In several standards, an issuing authority is mentioned that will keep a central registry of known Providers and Operators.
At this moment, the following countries have an authority that keeps track of the known providers and operators:

[[terminology_the_netherlands]]
==== The Netherlands, Belgium and Luxembourg (BeNeLux)

The Dutch foundation, named http://www.eviolin.nl[eViolin] keeps the registry for The Netherlands, Belgium and Luxembourg.

* The list of operator IDs and provider IDs can be viewed on their website http://www.eviolin.nl/index.php/leden/[eViolin/Leden].

[[terminology_germany]]
==== Germany

The BDEW organisation keeps the registry for Germany in their general code number service https://bdew-codes.de/[bdew-codes.de].

* https://bdew-codes.de/Codenumbers/EMobilityId/ProviderIdList[Provider ID List] See https://bdew-codes.de/Codenumbers/EMobilityId/ProviderIdList[https://bdew-codes.de/Codenumbers/EMobilityId/ProviderIdList]
* https://bdew-codes.de/Codenumbers/EMobilityId/OperatorIdList[EVSE Operator ID List] See https://bdew-codes.de/Codenumbers/EMobilityId/OperatorIdList[https://bdew-codes.de/Codenumbers/EMobilityId/OperatorIdList]

[[terminology_austria]]
==== Austria

Austrian Mobile Power GmbH maintains a registry for Austria. This list is not publicly available.
For more information visit http://austrian-mobile-power.at/tools/id-vergabe/information/[austrian-mobile-power.at]

[[terminology_france]]
==== France

The AFIREV* organisation will keep/keeps the registry for France. It provides operation Id for CPO and eMSP in compliance with eMI3 id structure. The prefix of these Ids is the “fr” country code. AFIREV will also be in charge of the definition of EVSE-Id structure, Charging-Pool-Id structure (location), and Contract-Id structure for France. AFIREV bases its requirements and recommendations on eMI3 definitions.

AFIREV stands for: Association Française pour l’Itinérance de la Recharge Électrique des Véhicules

[[terminology_charging_topology]]
=== Charging topology

The charging topology, as relevant to the eMSP, consists of three entities:

* _Connector_ is a specific socket or cable available for the EV to make use of.
* _EVSE_ is the part that controls the power supply to a single EV in a single session. An EVSE may provide multiple connectors but only one of these can be active at the same time.
* _Location_ is a group of one or more EVSEs that belong together geographically or spatially.

.Topology
image::images/topology.svg[Topology]

A Location is typically the exact location of one or more EVSEs, but it can also be the entrance of a parking garage or a gated community. It is up to the CPO to use whatever makes the most sense in a specific situation. Once arrived at the location, any further instructions to reach the EVSE from the Location are stored in the EVSE object itself (such as the floor number, visual identification or manual instructions).

[[terminology_variable_names]]
=== Variable names

In order to prevent issues with Capitals in variable names, the naming in JSON is not CamelCase but snake_case. All variables are lowercase and include an underscore for a space.

[[terminology_cardinality]]
=== Cardinality

When defining the cardinality of a field, the following symbols are used throughout this document:

[cols="1,9,1",options="header"]
|===
|Symbol |Description |Type 

|? |An optional object. If not set, it might be `null`, or the field might be omitted. When the field is omitted and it has a default value, the value is the default value. |Object 
|1 |Required object. |Object 
|* |A list of zero or more objects. If empty, it might be `null`, `[]` or the field might be omitted. |[Object] 
|+ |A list of at least one object. |[Object] 
|===