:numbered:
== Types

=== CiString _type_

Case Insensitive String. Only printable ASCII allowed.

=== DateTime _type_

All timestamps are formatted as string(25) using the combined date and time format from the ISO 8601 standard.
All timestamps SHALL be in UTC.
The absence of the timezone designator implies a UTC timestamp.

Example:

[source]
----
2015-06-29T20:39:09Z
2015-06-29T20:39:09
2016-12-29T17:45:09Z
2016-12-29T17:45:09
----

Note: +00:00 is not the same as UTC.

=== DisplayText _class_

|===
|Property |Type |Card. |Description 

|language |link:#15-string-type[string](2) |1 |Language Code ISO 639-1 
|text |link:#15-string-type[string](512) |1 |Text to be displayed to a end user. No markup, html etc. allowed. 
|===

Example:

[source]
----
{
  "language": "en",
  "text": "Standard Tariff"
}
----

=== number _type_

Numbers in OCPI are formatted as JSON numbers.
Unless mentioned otherwise, numbers use 4 decimals and a _sufficiently large amount_ of digits.

=== string _type_

Case Sensitive String. Only printable ASCII allowed. All strings in
messages and enumerations are case sensitive, unless explicitly stated
otherwise.

=== URL _type_

An URL a string(255) type following the http://www.w3.org/Addressing/URL/uri-spec.html[w3.org spec].