@startuml

skinparam agent {
	roundCorner 8
}

skinparam rectangle {
	roundCorner 8
}

left to right direction

rectangle PLATFORM as MSPPP {
  agent eMSP1
  agent eMSP2
  agent eMSP3
}

rectangle PLATFORM as CPOPP {
  agent CPO1
  agent CPO2
}

MSPPP -- CPOPP: OCPI


'following is only to fix layout
eMSP1 -[hidden]- CPO1
eMSP3 -[hidden]- CPO2

@enduml