@startuml

skinparam agent {
	roundCorner 8
}

skinparam rectangle {
	roundCorner 8
}

left to right direction

rectangle PLATFORM as MSP1 {
  agent eMSP1
  agent eMSP2
}

rectangle PLATFORM as MSP2 {
  agent eMSP3
  agent eMSP4
}

rectangle PLATFORM as MSP3 {
  agent eMSP5
}

rectangle PLATFORM as CPOP1 {
  agent CPO1
  agent CPO2
}

rectangle PLATFORM as CPOP2 {
  agent CPO3
  agent CPO4
}

rectangle PLATFORM as CPOP3 {
  agent CPO5
}

agent Hub

MSP1--Hub: OCPI
MSP2--Hub: OCPI
MSP3--Hub: OCPI
Hub--CPOP1: OCPI
Hub--CPOP2: OCPI
Hub--CPOP3: OCPI

MSP1--CPOP1
MSP3--CPOP3

@enduml