@startuml
hide footbox
participant "eMSP system" as MSP
participant "CPO system" as CPO

MSP -> CPO : POST: Send Booking request()
activate MSP
activate CPO
CPO -> MSP : status_code = 1000, data: {Booking { status = PENDING }}
deactivate MSP
||45||
CPO -> CPO: Checking if the booking timeslot is available, and is available

CPO  ->  MSP:  PUT: https://server.com/bookings/booking/ABC123\n     Booking(status = RESERVED, ........)
activate MSP
MSP --> CPO:
deactivate MSP
deactivate CPO

MSP -> CPO : POST ()
activate MSP
activate CPO
CPO -> MSP : status_code = 1000, data: {Booking { status = RESERVED, REQUESTS[{status = PENDING}] }}
deactivate MSP
||45||
CPO -> CPO: Checking if change is possible

CPO  ->  MSP:  PUT: https://server.com/bookings/booking/ABC123\n     Booking(status = RESERVED, ........)
activate MSP
MSP --> CPO:
deactivate MSP
deactivate CPO

CPO -> CPO

@enduml
