@startuml

participant CPO as CPO
participant MSP as MSP

CPO -> MSP: CDR 1

CPO -> MSP: CDR 2

CPO -> MSP: CDR 3

== March ends ==

CPO -> MSP: CDR 4

note over MSP: MSP runs billing for sessions of March
MSP -> CPO: publish Invoice Reconciliation Record: \n{ \n   "country_code": "NL",\n   "party_id": "TNM",\n   "id": "3", \n   "invoice_id": "INV202303", \n   "cdrs": [{"id": "a"}, {"id": "b"}, {"id": "c"}], \n   "last_updated": "2015-04-01T21:59:59Z",   \n}
note over MSP: MSP emails invoice PDF to CPO

note over CPO: CPO checks invoice total from MSP

@enduml
